### PR TITLE
Feat: A simple and minimalist comment system.

### PR DESCRIPTION
**Pull request by MHuiG**
The addition of this comment system can give users more choices.

Minivaline is an optimized Valine, just like its name.

After all work is completed, your project will be included in AWESOME-MiniValine

That sounds great！

https://github.com/MiniValine/AWESOME-MiniValine

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/MiniValine/AWESOME-MiniValine">MiniValine/AWESOME-MiniValine</a></strong></div><div>:sunglasses: Minimalist MiniValine, AWESOME MiniValine! - MiniValine/AWESOME-MiniValine</div></blockquote>

### CODE REVIEW

**Comment by Shen-Yu** [comment]
@MHuiG 
Hello~
First of all, thanks for your contribution, MiniValine looks fast and cool. i'm glad to see this comment system, but i suggest you to fix these code before i merge this PR:

- Can you add `theme.minivaline && theme.minivaline.enable` in `article.ejs`, just like Valine.
- Can you change a id name rather than `vcomments`, i'm worring about if this will cause conflicts with Valine. as well as the styles.
- Personally, i'd prefer `jsdeliver` to `unpkg`, cause i think it's faster.

**Comment by MHuiG** [comment]
MiniValine version 2.x beta :point_right: [内测邀请](https://github.com/MiniValine/MiniValine) :point_left:

**Comment by Shen-Yu** [comment]
@MHuiG 之前那个XSS漏洞，我以为你不维护了呢。。
image

**Comment by Shen-Yu** [comment]
哎，还是希望能够稳定一点，不然每次版本也要更新

**Comment by MHuiG** [comment]
> @MHuiG 之前那个XSS漏洞，我以为你不维护了呢。。
> image

Gitalk网络被墙了。。。又换回来了

**Pull request merged**
